### PR TITLE
Add sphinx documentation

### PR DESCRIPTION
**Pull request by satyaog**
The documentation gives an example of how to load the ImageNet dataset in a PyTorch model using Benzina

### CODE REVIEW

**Comment by satyaog** [comment]
@obilaniu , Here is a short sphinx doc for Benzina. It currently only shows how Benzina could be used to load ImageNet into a PyTorch model. Since #5 is not merged, the references are to the current master state so depending on what gets merged, I will probably need to update this pr so it's here mostly for you to have a look.

**Comment by obilaniu** [comment]
I'd really like to avoid `Makefile`'s of any kind. That's why I adopted Meson as a cross-platform build solution. If you look in the folder `doc/` (the standard name for the documentation folder of most GNU and system packages), there's now a `meson.build` file for you to play with, and it has the beginning of a Meson `custom_target()`. That's probably the right thing to use instead.

**Comment by satyaog** [comment]
Sure I'll convert the `Makefile` to meson and use the doc directory. The only reason why `Makefile` and docs were used was because of the tuto on read the docs which setups a boiling plate for sphinx. Here it is btw in case you want to have a look: https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html

**Comment by satyaog** [comment]
I've rebased on the current master and removed the make files

**Comment by nouiz** [comment]
It would be great to have a link in the github main page that point to the new doc.

**Pull request merged**
